In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('main_task.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Restaurant_id      40000 non-null  object
 1   City               40000 non-null  object
 2   Cuisine Style      30717 non-null  object
 3   Ranking            40000 non-null  float64
 4   Rating             40000 non-null  float64
 5   Price Range        26114 non-null  object
 6   Number of Reviews  37457 non-null  float64
 7   Reviews            40000 non-null  object
 8   URL_TA             40000 non-null  object
 9   ID_TA              40000 non-null  object
dtypes: float64(3), object(7)
memory usage: 3.1+ MB

1. Restaurant_id — идентификационный номер ресторана / сети ресторанов;
2. City — город, в котором находится ресторан;
3. Cuisine Style — кухня или кухни, к которым можно отнести блюда, предлагаемые в ресторане;
4. Ranking — место, которое занимает данный ресторан среди всех ресторанов своего города;
5. Rating — рейтинг ресторана по данным TripAdvisor (именно это значение должна будет предсказывать модель);
6. Price Range — диапазон цен в ресторане;
7. Number of Reviews — количество отзывов о ресторане;
8. Reviews — данные о двух отзывах, которые отображаются на сайте ресторана;
9. URL_TA — URL страницы ресторана на TripAdvisor;
10. ID_TA — идентификатор ресторана в базе данных TripAdvisor.

In [18]:
#checking which columns contain null values
df.isna().any()[lambda x: x]

Cuisine Style        True
Price Range          True
Number of Reviews    True
dtype: bool

In [26]:
df.head(20)

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,id_5569,Paris,"['European', 'French', 'International']",5570.0,3.5,$$ - $$$,194.0,"[['Good food at your doorstep', 'A good hotel ...",/Restaurant_Review-g187147-d1912643-Reviews-R_...,d1912643
1,id_1535,Stockholm,NaN,1537.0,4.0,NaN,10.0,"[['Unique cuisine', 'Delicious Nepalese food']...",/Restaurant_Review-g189852-d7992032-Reviews-Bu...,d7992032
2,id_352,London,"['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...",353.0,4.5,$$$$,688.0,"[['Catch up with friends', 'Not exceptional'],...",/Restaurant_Review-g186338-d8632781-Reviews-RO...,d8632781
3,id_3456,Berlin,NaN,3458.0,5.0,NaN,3.0,"[[], []]",/Restaurant_Review-g187323-d1358776-Reviews-Es...,d1358776
4,id_615,Munich,"['German', 'Central European', 'Vegetarian Fri...",621.0,4.0,$$ - $$$,84.0,"[['Best place to try a Bavarian food', 'Nice b...",/Restaurant_Review-g187309-d6864963-Reviews-Au...,d6864963
5,id_1418,Oporto,NaN,1419.0,3.0,NaN,2.0,"[['There are better 3 star hotel bars', 'Amazi...",/Restaurant_Review-g189180-d12503536-Reviews-D...,d12503536
6,id_1720,Milan,"['Italian', 'Pizza']",1722.0,4.0,$,50.0,"[['Excellent simple local eatery.', 'Excellent...",/Restaurant_Review-g187849-d5808504-Reviews-Pi...,d5808504
7,id_825,Bratislava,['Italian'],826.0,3.0,NaN,9.0,"[['Wasting of money', 'excellent cuisine'], ['...",/Restaurant_Review-g274924-d3199765-Reviews-Ri...,d3199765
8,id_2690,Vienna,NaN,2692.0,4.0,NaN,NaN,"[[], []]",/Restaurant_Review-g190454-d12845029-Reviews-G...,d12845029
9,id_4209,Rome,"['Italian', 'Pizza', 'Fast Food']",4210.0,4.0,$,55.0,"[['Clean efficient staff', 'Nice little pizza ...",/Restaurant_Review-g187791-d8020681-Reviews-Qu...,d8020681
10,id_6578,Barcelona,NaN,6579.0,3.0,NaN,6.0,"[[], []]",/Restaurant_Review-g187497-d10696479-Reviews-R...,d10696479
11,id_5312,London,"['Italian', 'Pizza', 'Vegetarian Friendly']",5321.0,4.0,$$ - $$$,42.0,"[['Not bad for Canary Wharf', 'To be a pilgrim...",/Restaurant_Review-g186338-d12402429-Reviews-P...,d12402429
12,id_4066,London,"['Italian', 'Pizza', 'Vegetarian Friendly', 'G...",4073.0,3.5,$$ - $$$,286.0,"[['Great service, good za', 'Lovely, relaxed a...",/Restaurant_Review-g186338-d2259559-Reviews-Ma...,d2259559
13,id_4637,Berlin,"['Vegetarian Friendly', 'Gluten Free Options']",4639.0,4.5,$$ - $$$,10.0,"[['What a great spot!', 'Healthy superfoods, v...",/Restaurant_Review-g187323-d12107166-Reviews-L...,d12107166
14,id_4773,Madrid,"['Mediterranean', 'Spanish', 'Healthy']",4776.0,4.0,$$ - $$$,7.0,"[[], []]",/Restaurant_Review-g187514-d10859423-Reviews-B...,d10859423
15,id_1401,Dublin,['Cafe'],1405.0,4.0,$$ - $$$,28.0,"[['Lovely food', 'Great coffee'], ['12/01/2017...",/Restaurant_Review-g186605-d6633059-Reviews-Gr...,d6633059
16,id_5257,Berlin,"['Japanese', 'Asian', 'Thai', 'Vietnamese']",5259.0,4.0,NaN,3.0,"[['This is a real hidden Sushi-gem'], ['04/12/...",/Restaurant_Review-g187323-d10266473-Reviews-A...,d10266473
17,id_11121,London,"['Bar', 'Pub']",11131.0,4.5,$$ - $$$,7.0,"[['gin tour venue', 'Gin Tour'], ['02/28/2017'...",/Restaurant_Review-g186338-d8659568-Reviews-46...,d8659568
18,id_3127,Berlin,['German'],3129.0,4.0,$$ - $$$,12.0,"[['Nice stay, very good hotel', 'great residen...",/Restaurant_Review-g187323-d3702312-Reviews-Al...,d3702312
19,id_2791,Brussels,['Chinese'],2792.0,3.0,$$ - $$$,12.0,"[['Seriously, is this a restaurant?', 'Not tha...",/Restaurant_Review-g947638-d8155327-Reviews-Ho...,d8155327

# Задача 
Код для создания модели предоставлен, но чтобы модель заработала, в неё нужно загрузить правильные данные, что и явяляется моей задачей.

### RandomForestRegression

In [29]:
# Разбиваем датафрейм на части, необходимые для обучения и тестирования модели  
# Х - данные с информацией о ресторанах, у - целевая переменная (рейтинги ресторанов)  
X = df.drop(['Restaurant_id', 'Rating'], axis = 1)  
y = df['Rating']  

# Загружаем специальный инструмент для разбивки:  
from sklearn.model_selection import train_test_split  

# Наборы данных с меткой "train" будут использоваться для обучения модели, "test" - для тестирования.  
# Для тестирования мы будем использовать 25% от исходного датасета.  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [34]:
# Импортируем необходимые библиотеки:  
from sklearn.ensemble import RandomForestRegressor # инструмент для создания и обучения модели  
from sklearn import metrics # инструменты для оценки точности модели  

# Создаём модель  
regr = RandomForestRegressor(n_estimators=100)  

# Обучаем модель на тестовом наборе данных  
regr.fit(X_train, y_train)  

# Используем обученную модель для предсказания рейтинга ресторанов в тестовой выборке.  
# Предсказанные значения записываем в переменную y_pred  
y_pred = regr.predict(X_test)

ValueError: could not convert string to float: 'Lisbon'

Машинное обучение - это работа с числами, и для обучения модели мы должны передать ей исключительно количественные данные.

Итак, мы выяснили, что для корректной работы все данные в датафрейме, который вы будете использовать при обучении модели, должны быть в форматах int или float. Есть и ещё одно жёсткое ограничение: в столбцах не должно быть None-значений. В реальных проектах в индустрии используются разные подходы к работе с None-значениями. Если позволяют условия, то строки, содержащие неполные данные, просто удаляют из датасета. Однако в задачах по машинному обучению эта стратегия не используется никогда, потому что настоящие герои никогда не ищут лёгких путей :) Вместо каждого NaN вам нужно будет вычислить и поместить в ячейку максимально близкое к реальности значение.

Таким образом, чтобы код, отвечающий за обучение модели, заработал, мы должны использовать в нём датафрейм, содержащий только количественные признаки и не содержащий None-значений.

Для оценки точности прогнозов, сделанных моделью, мы будем использовать метрику (показатель), которая называется Mean Absolute Error, и представляет собой среднее абсолютное значение отклонения предсказанных значений от фактических:

In [37]:
# Сравниваем предсказанные значения (y_pred) с реальными (y_test), и смотрим насколько они в среднем отличаются  
# Метрика называется Mean Absolute Error (MAE) и показывает среднее отклонение предсказанных значений от фактических.  
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))

NameError: name 'y_pred' is not defined